In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys, platform, os
print(sys.executable)
print(platform.python_version())

/Users/AH45807/project/idiscovery-deep-research/.venv/bin/python
3.13.5

In [3]:
import pandas as pd

# Set the option to display all columns
pd.set_option('display.max_columns', None)

# You might also want to set max_colwidth to None to prevent column content truncation
pd.set_option('display.max_colwidth', None)
from datetime import datetime
import time
from collections import Counter
import pathlib
from pathlib import Path
from datetime import date
from collections import defaultdict
from dotenv import load_dotenv
# load_dotenv("/mnt/jupyter/hru/idiscovery-2pm-rule-extraction-hru/.env")

load_dotenv("/Users/AH45807/project/idiscovery-deep-research/.env")

True

In [4]:
from deep_research_utils.app_constant import AppConstants

2026-04-22 17:06:32,892 - policy_extractor.system - INFO - === Policy Extractor Logging Initialized ===
2026-04-22 17:06:32,893 - policy_extractor.system - INFO - Log directory: /Users/AH45807/project/idiscovery-deep-research/packages/core/src/deep_research_core/logs
2026-04-22 17:06:32,893 - policy_extractor.system - INFO - Max file size: 50.0MB
2026-04-22 17:06:32,894 - policy_extractor.system - INFO - Backup count: 10
2026-04-22 17:06:32,894 - policy_extractor.system - INFO - Console output enabled: True
2026-04-22 17:06:32,895 - policy_extractor.system - INFO - Console log level: INFO
2026-04-22 17:06:32,895 - policy_extractor.system - INFO - Console stream: stdout
2026-04-22 17:06:32,896 - policy_extractor.system - INFO - Process ID: 76542
2026-04-22 17:06:32,896 - policy_extractor.system - INFO - Component log levels:
2026-04-22 17:06:32,897 - policy_extractor.system - INFO -   policy_extractor.snowflake_store: WARNING
2026-04-22 17:06:32,897 - policy_extractor.system - INFO -   policy_extractor.snowflake_bulk_operations: WARNING
2026-04-22 17:06:32,898 - policy_extractor.system - INFO -   policy_extractor.pipeline: INFO
2026-04-22 17:06:32,898 - policy_extractor.system - INFO -   policy_extractor.api: INFO
2026-04-22 17:06:32,898 - policy_extractor.system - INFO -   policy_extractor.rendering: INFO
2026-04-22 17:06:32,899 - policy_extractor.system - INFO -   policy_extractor.url_extraction: INFO
2026-04-22 17:06:32,899 - policy_extractor.system - INFO -   policy_extractor.chunking: DEBUG

In [5]:
from deep_research_utils import SnowparkHelper

snowpark_programmatic_connection_parameters = {
    "account" : os.environ["SNOWFLAKE_ACCOUNT"],
    "user": os.environ["SNOWFLAKE_USER"],
    "password": os.environ["SNOWFLAKE_SECRET"],
    "warehouse": os.environ["SNOWFLAKE_WAREHOUSE"],
    "database": os.environ["SNOWFLAKE_DATABASE"],
    "schema": os.environ["SNOWFLAKE_SCHEMA"]
}

snowpark = SnowparkHelper(
    connection_type="programmatic",
    batch_size=10000,        # Larger batches
    max_workers=6,           # Parallel processing
    enable_metrics=True,     # Performance tracking
    connection_pool_size=4,  # Connection pooling
    **snowpark_programmatic_connection_parameters
)

2026-04-22 17:06:36,325 - deep_research_utils.snowflake_helper - INFO - Snowflake session created successfully
2026-04-22 17:06:43,614 - deep_research_utils.snowflake_helper - INFO - Initialized connection pool with 3 additional sessions

In [6]:
from deep_research_utils import EHAPBase
EHAP = EHAPBase(base_url=os.environ.get("EHAP_BASE_URL"),
                client_id=os.environ.get("EHAP_CLIENT_ID"),
                client_secret=os.environ.get("EHAP_CLIENT_SECRET"),
                verify=os.environ.get("SSL_CERT_FILE"))

In [7]:
from langchain_openai import ChatOpenAI

In [8]:
# Chat model
model_medium_reasoning = ChatOpenAI(
    model="gpt-5.4",
    api_key=EHAP.get_token(),
    # output_version="completions/v1", # todo: check the version EHAP supports.
    # https://reference.langchain.com/python/langchain-openai/chat_models/base/ChatOpenAI
    extra_body={
        "reasoning_effort": "medium",  # Choices: "low", "medium", "high"
        "summary": None  # Choices: 'detailed', 'auto', or None 
    }
)

2026-04-22 17:06:44,323 - deep_research_utils.ehap - INFO - Requesting new access token from https://api.horizon.elevancehealth.com/v2/oauth2/token with client_id: BPWOQiwbyghnhWBaBzRYJhL3dU22bbb0
2026-04-22 17:06:44,501 - deep_research_utils.ehap - INFO - Access token generated successfully.
**TOKEN** **TOKEN** **TOKEN**

/Users/AH45807/project/idiscovery-deep-research/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.horizon.elevancehealth.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [9]:
# ai_msg = model_medium_reasoning.invoke("What are the benefits of LangChain?")

# # Access the text content
# print(ai_msg.content)
# print(ai_msg.response_metadata)

# Step 1: Raja's Anomaly Detection

In [10]:
df_insights = pd.read_csv("/Users/AH45807/project/idiscovery-deep-research/packages/core/src/deep_research_core/coc_cmn_data_insght_stg-u01 2.csv")
print(df_insights.shape)
df_insights.head(2)

(24, 8)

,SNAP_YEAR_MNTH_NBR,TRND_TM_PRD_END_MNTH_NBR,TRND_TM_PRD_CD,LOB_CD,LOB_SHRT_DESC,STATSCL_MDL_CD,INSIGHTS_TYPE,JSON_TXT
0,202603,202512,R12,MCM006,Commercial,IP AUTH,KEY_INSIGHT,"{\n ""top_contributors"": {\n ""drgs"": [\n {\n ""insight"": ""Showed the highest growth in non-participating paid amounts."",\n ""name"": ""Vaginal Delivery without Sterilization or D&C with CC"",\n ""percentage_change"": ""+41%""\n },\n {\n ""insight"": ""Experienced significant growth in non-participating paid amounts."",\n ""name"": ""Vaginal Delivery without Sterilization or D&C without CC/MCC"",\n ""percentage_change"": ""+40%""\n },\n {\n ""insight"": ""Had a notable increase in non-participating paid amounts."",\n ""name"": ""Cesarean Section without Sterilization with MCC"",\n ""percentage_change"": ""+33%""\n }\n ],\n ""provider_trends"": [\n {\n ""insight"": ""Experienced a significant spike in non-participating paid amounts."",\n ""name"": ""JOHN PETER SMITH HOSPITAL"",\n ""percentage_change"": ""+4433%""\n },\n {\n ""insight"": ""Showed a substantial increase in non-participating paid amounts."",\n ""name"": ""EMORY DECATUR HOSPITAL"",\n ""percentage_change"": ""+356%""\n },\n {\n ""insight"": ""Had a notable rise in non-participating paid amounts."",\n ""name"": ""GRADY MEMORIAL HOSPITAL"",\n ""percentage_change"": ""+188%""\n }\n ],\n ""states"": [\n {\n ""insight"": ""Saw a significant increase in non-participating paid amounts."",\n ""name"": ""ME"",\n ""percentage_change"": ""+22%""\n },\n {\n ""insight"": ""Experienced a notable rise in non-participating paid amounts."",\n ""name"": ""CO"",\n ""percentage_change"": ""+13%""\n }\n ]\n },\n ""whats_happening"": ""Non-participating paid amounts are rising, primarily driven by a 3.35% increase in authorizations.""\n}"
1,202603,202512,YTD,MCM006,Commercial,IP AUTH,KEY_INSIGHT,"{\n ""top_contributors"": {\n ""drgs"": [\n {\n ""insight"": ""Had a substantial growth in non-participating paid amounts."",\n ""name"": ""Vaginal Delivery without Sterilization or D&C with CC"",\n ""percentage_change"": ""+41%""\n },\n {\n ""insight"": ""Showed significant growth in non-participating paid amounts."",\n ""name"": ""Vaginal Delivery without Sterilization or D&C without CC/MCC"",\n ""percentage_change"": ""+40%""\n },\n {\n ""insight"": ""Experienced notable growth in non-participating paid amounts."",\n ""name"": ""Cesarean Section without Sterilization with MCC"",\n ""percentage_change"": ""+33%""\n }\n ],\n ""provider_trends"": [\n {\n ""insight"": ""Experienced a significant spike in non-participating paid amounts."",\n ""name"": ""JOHN PETER SMITH HOSPITAL"",\n ""percentage_change"": ""+4433%""\n },\n {\n ""insight"": ""Showed a substantial increase in non-participating paid amounts."",\n ""name"": ""EMORY DECATUR HOSPITAL"",\n ""percentage_change"": ""+356%""\n },\n {\n ""insight"": ""Had a notable rise in non-participating paid amounts."",\n ""name"": ""GRADY MEMORIAL HOSPITAL"",\n ""percentage_change"": ""+188%""\n }\n ],\n ""states"": [\n {\n ""insight"": ""Saw a significant increase in non-participating paid amounts."",\n ""name"": ""ME"",\n ""percentage_change"": ""+22%""\n },\n {\n ""insight"": ""Experienced a notable rise in non-participating paid amounts."",\n ""name"": ""CO"",\n ""percentage_change"": ""+13%""\n }\n ]\n },\n ""whats_happening"": ""Non-participating paid amounts are rising, primarily driven by a 3.35% increase in authorizations.""\n}"

In [11]:
df_insights.INSIGHTS_TYPE.value_counts()

INSIGHTS_TYPE
KEY_INSIGHT    12
DEEP_DIVE      12
Name: count, dtype: int64

In [12]:
import json

In [13]:
# view sample insights
deep_dive = json.loads(df_insights.JSON_TXT.iloc[13])
print(deep_dive)

{
  "report_title": "IP AUTHORIZATION INSIGHTS - COMMERCIAL LOB, R12 PERIOD",
  "national_summary": {
    "description": "National Total Authorizations: 141,851"
  },
  "top_state_drivers": {
    "section_title": "TOP STATE DRIVERS",
    "states": [
      {
        "state_name": "CO",
        "overview": "CO has 5,898 auths out of 141,851 nationally (4.16% of the national total).",
        "medical_necessity_review_mix": "In CO, 41.88% of authorizations require Medical Necessity review (2,470 of 5,898), 14.99% do not require Medical Necessity review (884 of 5,898).",
        "service_driver": "In CO, of total 5,898 authorizations IP Med/Surg contributes 3,850 authorizations, accounting for 65.27%; IP BH contributes 1,469 authorizations, accounting for 24.90%; IP OB Dlvry NB contributes 524 authorizations, accounting for 8.89%; NF contributes 60 authorizations, accounting for 1.02%.",
        "authorization_status_mix": "In CO, Out of 5,898 authorizations received, 5,221 are in Approved status, accounting for 88.52% of total authorizations, 485 are in Partial status, accounting for 8.22% of total authorizations, 138 are in Not Approved status, accounting for 2.34% of total authorizations, 52 are in No Decision status, accounting for 0.88% of total authorizations, 2 are in None status, accounting for 0.03% of total authorizations.",
        "approved_breakdown": [
          "Of 5,221 approved authorizations, Medical Necessity review approved cases are 5,113, which is 97.93% of approved authorizations; Administrative review approved cases are 8, which is 0.15% of approved authorizations."
        ],
        "denied_breakdown": [
          "Of 138 denied authorizations, Appealed authorizations are 24, accounting for 17.39%.",
          "Overturned cases are 3, accounting for 2.17% of total denials.",
          "Upheld cases are 15, accounting for 10.87% of total denials."
        ]
      },
      {
        "state_name": "ME",
        "overview": "ME has 1,899 auths out of 141,851 nationally (1.34% of the national total).",
        "medical_necessity_review_mix": "In ME, 46.87% of authorizations require Medical Necessity review (890 of 1,899), 18.38% do not require Medical Necessity review (349 of 1,899).",
        "service_driver": "In ME, of total 1,899 authorizations IP Med/Surg contributes 1,205 authorizations, accounting for 63.45%; IP BH contributes 527 authorizations, accounting for 27.75%; IP OB Dlvry NB contributes 146 authorizations, accounting for 7.69%; NF contributes 27 authorizations, accounting for 1.42%.",
        "authorization_status_mix": "In ME, Out of 1,899 authorizations received, 1,736 are in Approved status, accounting for 91.42% of total authorizations, 135 are in Partial status, accounting for 7.11% of total authorizations, 24 are in Not Approved status, accounting for 1.26% of total authorizations, 4 are in No Decision status, accounting for 0.21% of total authorizations, 0 are in None status, accounting for 0.00% of total authorizations.",
        "approved_breakdown": [
          "Of 1,736 approved authorizations, Medical Necessity review approved cases are 1,693, which is 97.52% of approved authorizations."
        ],
        "denied_breakdown": [
          "Of 24 denied authorizations, Appealed authorizations are 3, accounting for 12.50%.",
          "Overturned cases are 0, accounting for 0.00% of total denials.",
          "Upheld cases are 1, accounting for 4.17% of total denials."
        ]
      }
    ]
  },
  "top_drg_drivers": {
    "section_title": "TOP DRG DRIVERS",
    "drgs": [
      {
        "drg_name": "Vaginal Delivery without Sterilization or D&C without CC/MCC",
        "overview": "Vaginal Delivery without Sterilization or D&C without CC/MCC has 4,093 auths out of 141,851 nationally (2.89% of the national total).",
        "medical_necessity_review_mix": "In Vaginal Delivery without Sterilization or D&C without CC/MCC, 24.65% of authorizations require Medical Necessity review (1,009 of 4,093), 68.34% do not require Medical Necessity review (2,797 of 4,093).",
        "service_driver": "In Vaginal Delivery without Sterilization or D&C without CC/MCC, of total 4,093 authorizations IP OB Dlvry NB contributes 4,093 authorizations, accounting for 100.00%.",
        "authorization_status_mix": "In Vaginal Delivery without Sterilization or D&C without CC/MCC, Out of 4,093 authorizations received, 3,397 are in Approved status, accounting for 83.00% of total authorizations, 297 are in No Decision status, accounting for 7.26% of total authorizations, 293 are in Partial status, accounting for 7.16% of total authorizations, 106 are in Not Approved status, accounting for 2.59% of total authorizations, 0 are in None status, accounting for 0.00% of total authorizations.",
        "approved_breakdown": [
          "Of 3,397 approved authorizations, Medical Necessity review approved cases are 1,759, which is 51.78% of approved authorizations; Administrative review approved cases are 323, which is 9.51% of approved authorizations."
        ],
        "denied_breakdown": [
          "Of 106 denied authorizations, Appealed authorizations are 6, accounting for 5.66%.",
          "Overturned cases are 0, accounting for 0.00% of total denials.",
          "Upheld cases are 2, accounting for 1.89% of total denials."
        ]
      },
      {
        "drg_name": "Cesarean Section without Sterilization without CC/MCC",
        "overview": "Cesarean Section without Sterilization without CC/MCC has 1,570 auths out of 141,851 nationally (1.11% of the national total).",
        "medical_necessity_review_mix": "In Cesarean Section without Sterilization without CC/MCC, 24.20% of authorizations require Medical Necessity review (380 of 1,570), 67.26% do not require Medical Necessity review (1,056 of 1,570).",
        "service_driver": "In Cesarean Section without Sterilization without CC/MCC, of total 1,570 authorizations IP OB Dlvry NB contributes 1,570 authorizations, accounting for 100.00%.",
        "authorization_status_mix": "In Cesarean Section without Sterilization without CC/MCC, Out of 1,570 authorizations received, 1,381 are in Approved status, accounting for 87.96% of total authorizations, 84 are in Partial status, accounting for 5.35% of total authorizations, 71 are in No Decision status, accounting for 4.52% of total authorizations, 34 are in Not Approved status, accounting for 2.17% of total authorizations, 0 are in None status, accounting for 0.00% of total authorizations.",
        "approved_breakdown": [
          "Of 1,381 approved authorizations, Medical Necessity review approved cases are 772, which is 55.90% of approved authorizations; Administrative review approved cases are 122, which is 8.83% of approved authorizations."
        ],
        "denied_breakdown": [
          "Of 34 denied authorizations, no appeals to report."
        ]
      },
      {
        "drg_name": "Vaginal Delivery without Sterilization or D&C with CC",
        "overview": "Vaginal Delivery without Sterilization or D&C with CC has 1,405 auths out of 141,851 nationally (0.99% of the national total).",
        "medical_necessity_review_mix": "In Vaginal Delivery without Sterilization or D&C with CC, 29.75% of authorizations require Medical Necessity review (418 of 1,405), 62.99% do not require Medical Necessity review (885 of 1,405).",
        "service_driver": "In Vaginal Delivery without Sterilization or D&C with CC, of total 1,405 authorizations IP OB Dlvry NB contributes 1,405 authorizations, accounting for 100.00%.",
        "authorization_status_mix": "In Vaginal Delivery without Sterilization or D&C with CC, Out of 1,405 authorizations received, 1,121 are in Approved status, accounting for 79.79% of total authorizations, 142 are in Partial status, accounting for 10.11% of total authorizations, 105 are in No Decision status, accounting for 7.47% of total authorizations, 37 are in Not Approved status, accounting for 2.63% of total authorizations, 0 are in None status, accounting for 0.00% of total authorizations.",
        "approved_breakdown": [
          "Of 1,121 approved authorizations, Medical Necessity review approved cases are 640, which is 57.09% of approved authorizations; Administrative review approved cases are 123, which is 10.97% of approved authorizations."
        ],
        "denied_breakdown": [
          "Of 37 denied authorizations, Appealed authorizations are 3, accounting for 8.11%.",
          "Overturned cases are 0, accounting for 0.00% of total denials.",
          "Upheld cases are 1, accounting for 2.70% of total denials."
        ]
      }
    ]
  },
  "top_provider_drivers": {
    "section_title": "TOP PROVIDER DRIVERS",
    "providers": [
      {
        "provider_name": "CEDARS-SINAI MEDICAL CENTER",
        "overview": "CEDARS-SINAI MEDICAL CENTER has 912 auths out of 141,851 nationally (0.64% of the national total).",
        "medical_necessity_review_mix": "In CEDARS-SINAI MEDICAL CENTER, 82.89% of authorizations require Medical Necessity review (756 of 912), 15.68% do not require Medical Necessity review (143 of 912).",
        "service_driver": "In CEDARS-SINAI MEDICAL CENTER, of total 912 authorizations IP Med/Surg contributes 738 authorizations, accounting for 80.92%; IP OB Dlvry NB contributes 174 authorizations, accounting for 19.08%; IP BH contributes 0 authorizations, accounting for 0.00%.",
        "authorization_status_mix": "In CEDARS-SINAI MEDICAL CENTER, Out of 912 authorizations received, 780 are in Approved status, accounting for 85.53% of total authorizations, 86 are in Partial status, accounting for 9.43% of total authorizations, 36 are in Not Approved status, accounting for 3.95% of total authorizations, 10 are in No Decision status, accounting for 1.10% of total authorizations, 0 are in None status, accounting for 0.00% of total authorizations.",
        "approved_breakdown": [
          "Of 780 approved authorizations, Medical Necessity review approved cases are 685, which is 87.82% of approved authorizations; Administrative review approved cases are 65, which is 8.33% of approved authorizations."
        ],
        "denied_breakdown": [
          "Of 36 denied authorizations, Appealed authorizations are 2, accounting for 5.56%.",
          "Overturned cases are 0, accounting for 0.00% of total denials.",
          "Upheld cases are 2, accounting for 5.56% of total denials."
        ]
      },
      {
        "provider_name": "GRADY MEMORIAL HOSPITAL",
        "overview": "GRADY MEMORIAL HOSPITAL has 516 auths out of 141,851 nationally (0.36% of the national total).",
        "medical_necessity_review_mix": "In GRADY MEMORIAL HOSPITAL, 17.64% of authorizations require Medical Necessity review (91 of 516), 21.32% do not require Medical Necessity review (110 of 516).",
        "service_driver": "In GRADY MEMORIAL HOSPITAL, of total 516 authorizations IP Med/Surg contributes 479 authorizations, accounting for 92.83%; IP OB Dlvry NB contributes 20 authorizations, accounting for 3.88%; IP BH contributes 17 authorizations, accounting for 3.29%.",
        "authorization_status_mix": "In GRADY MEMORIAL HOSPITAL, Out of 516 authorizations received, 411 are in Approved status, accounting for 79.65% of total authorizations, 95 are in Partial status, accounting for 18.41% of total authorizations, 5 are in Not Approved status, accounting for 0.97% of total authorizations, 5 are in No Decision status, accounting for 0.97% of total authorizations, 0 are in None status, accounting for 0.00% of total authorizations.",
        "approved_breakdown": [
          "Of 411 approved authorizations, Medical Necessity review approved cases are 404, which is 98.30% of approved authorizations."
        ],
        "denied_breakdown": [
          "Of 5 denied authorizations, no appeals to report."
        ]
      },
      {
        "provider_name": "EMORY DECATUR HOSPITAL",
        "overview": "EMORY DECATUR HOSPITAL has 365 auths out of 141,851 nationally (0.26% of the national total).",
        "medical_necessity_review_mix": "In EMORY DECATUR HOSPITAL, 20.27% of authorizations require Medical Necessity review (74 of 365), 14.52% do not require Medical Necessity review (53 of 365).",
        "service_driver": "In EMORY DECATUR HOSPITAL, of total 365 authorizations IP Med/Surg contributes 268 authorizations, accounting for 73.42%; IP BH contributes 63 authorizations, accounting for 17.26%; IP OB Dlvry NB contributes 34 authorizations, accounting for 9.32%.",
        "authorization_status_mix": "In EMORY DECATUR HOSPITAL, Out of 365 authorizations received, 346 are in Approved status, accounting for 94.79% of total authorizations, 18 are in Partial status, accounting for 4.93% of total authorizations, 1 are in No Decision status, accounting for 0.27% of total authorizations, 0 are in None status, accounting for 0.00% of total authorizations.",
        "approved_breakdown": [
          "Of 346 approved authorizations, Medical Necessity review approved cases are 330, which is 95.38% of approved authorizations."
        ],
        "denied_breakdown": [
          "Of 0 denied authorizations, no appeals to report."
        ]
      },
      {
        "provider_name": "JOHN PETER SMITH HOSPITAL",
        "overview": "JOHN PETER SMITH HOSPITAL has 272 auths out of 141,851 nationally (0.19% of the national total).",
        "medical_necessity_review_mix": "In JOHN PETER SMITH HOSPITAL, 80.15% of authorizations require Medical Necessity review (218 of 272), 19.85% do not require Medical Necessity review (54 of 272).",
        "service_driver": "In JOHN PETER SMITH HOSPITAL, of total 272 authorizations IP Med/Surg contributes 173 authorizations, accounting for 63.60%; IP OB Dlvry NB contributes 67 authorizations, accounting for 24.63%; IP BH contributes 32 authorizations, accounting for 11.76%.",
        "authorization_status_mix": "In JOHN PETER SMITH HOSPITAL, Out of 272 authorizations received, 240 are in Approved status, accounting for 88.24% of total authorizations, 23 are in Partial status, accounting for 8.46% of total authorizations, 8 are in Not Approved status, accounting for 2.94% of total authorizations, 1 are in No Decision status, accounting for 0.37% of total authorizations, 0 are in None status, accounting for 0.00% of total authorizations.",
        "approved_breakdown": [
          "Of 240 approved authorizations, Medical Necessity review approved cases are 209, which is 87.08% of approved authorizations; Administrative review approved cases are 1, which is 0.42% of approved authorizations."
        ],
        "denied_breakdown": [
          "Of 8 denied authorizations, no appeals to report."
        ]
      }
    ]
  },
  "report_footer": {
    "status": "INSIGHTS GENERATION COMPLETE"
  }
}

In [14]:
# Chat model
llm = ChatOpenAI(
    model=AppConstants.EHAP_LLM_MODEL,
    api_key=EHAP.get_token(),
    # output_version="completions/v1", # todo: check the version EHAP supports.
    # https://reference.langchain.com/python/langchain-openai/chat_models/base/ChatOpenAI
    extra_body={
        "reasoning_effort": "medium",  # Choices: "low", "medium", "high"
        "summary": None  # Choices: 'detailed', 'auto', or None 
    }
)

In [ ]:
# PATTERN_SYSTEM_PROMPT = """You are a conservative pattern-extraction engine.

# Your task is to analyze any INPUT_JSON dynamically and return a flat pattern table.
# Do NOT hardcode report sections, field names, or business-specific labels.
# Infer repeated structures, entities, metrics, and patterns directly from the input.

# Your output is for downstream processing, so reliability matters more than coverage.

# PRIMARY OBJECTIVE
# Return the smallest set of distinct, high-signal, non-overlapping patterns needed to summarize the input.

# A good pattern:
# - captures a meaningful repeated structure,
# - summarizes multiple facts into one insight, or
# - identifies a true outlier / exception.

# A bad pattern:
# - repeats the same idea for each driver type,
# - restates an obvious fact already covered by another row,
# - creates one row just because a section exists,
# - calls out low-signal zeros or missing values with little business value.

# OUTPUT RULES
# - Return ONLY valid JSON.
# - Do not return markdown.
# - The output must be a single JSON object with:
#   - "schema_summary"
#   - "pattern_table"
# - Each row in "pattern_table" must use the exact same keys.
# - If a field does not apply, use null.
# - If no defensible patterns exist, return an empty pattern_table.
# - Preserve exact evidence text where possible.

# STRICT NON-HALLUCINATION RULES
# - Do not invent facts, numbers, entities, categories, dimensions, causes, recommendations, or evidence labels.
# - Do not assume missing fields exist.
# - Do not create a pattern unless it is explicitly supported by the input.
# - Do not create “Policy Evidence”, “Claims Evidence”, or any other evidence category unless the source supports that framing.
# - When unsure about evidence category, use "General Evidence".
# - Do not convert weak hints into strong conclusions.
# - Do not add interpretations about why the pattern happened.
# - Do not add actions, recommendations, or root causes.

# ANTI-REPETITION / DEDUPLICATION RULES
# - Internally generate candidate patterns first, then deduplicate before producing final output.
# - Normalize each candidate into:
#   - dimension
#   - finding
#   - population covered
# - If two candidates express the same finding on the same dimension with only different supporting examples, merge them into one broader row.
# - Do NOT emit one row per driver family for the same normalized finding.
# - Prefer one cross-entity row over several near-duplicate rows.
# - If the same pattern appears across multiple entity types, merge it into one row with:
#   - entity_type = "mixed"
#   - scope = "cross_entity"
#   - covered entity types stored in attributes_json
# - Before emitting any row, test:
#   - "Does this row add materially new information not already captured by an existing row?"
#   - If NO, do not emit it.
# - If two rows would have very similar pattern_title, leadership_summary, and description, keep only the stronger one.
# - Do not let the number of rows track the number of entities, sections, or driver groups.

# NOVELTY / MATERIALITY RULES
# Only keep a separate row when at least one of these is true:
# - it covers multiple entities and compresses repeated evidence into one insight
# - it shows a materially different direction or dominant category
# - it shows meaningful contrast or spread
# - it captures an extreme concentration, extreme value, or outlier
# - it captures a unique exception to a broader pattern

# Treat these as materially distinct examples:
# - roughly 10+ percentage-point spread
# - 2x+ magnitude difference
# - 90%+ concentration
# - 100% concentration
# - unique zero / unique missing / unique exception with clear business relevance

# SUPPRESSION RULES
# Suppress or merge patterns that are:
# - obvious and universal in the sample without adding contrast
# - low-signal zeros repeated across many entities
# - simple restatements of the same dominant status or same dominant service across separate driver groups
# - narrower versions of a broader pattern already captured

# PATTERN BUDGET
# - Target 3 to 7 rows total.
# - Only exceed 7 rows when the input clearly contains more than 7 distinct, non-overlapping, material patterns.
# - Fewer rows is better than repetitive rows.

# ROW SCHEMA
# Each pattern row must have exactly these keys:

# 1. pattern_id
# A deterministic id if possible.

# 2. pattern_title
# Short title, noun-phrase style, suitable for business readers.

# 3. leadership_summary
# One concise leadership-friendly sentence.
# Requirements:
# - 12 to 30 words
# - direct and factual
# - include the most important quantified takeaway when possible

# 4. description
# One factual sentence with slightly more detail than leadership_summary.
# Do not speculate.

# 5. pattern_type
# A generic label such as:
# - volume_pattern
# - share_pattern
# - dominant_category
# - concentration
# - status_pattern
# - review_pattern
# - approval_pattern
# - denial_pattern
# - appeal_pattern
# - residual_pattern
# - missing_data_pattern
# - zero_value_pattern
# - cross_entity_pattern
# - outlier_pattern
# - other_pattern

# 6. entity_type
# Best inferred entity type from the source.
# Examples: state, provider, drg, product, market, segment.
# If the pattern spans multiple entity types, use "mixed".
# If unknown, use "unknown_entity_type".

# 7. entity_name
# The entity name if tied to one entity.
# If the pattern is cross-entity or report-level, use null.

# 8. scope
# One of:
# - entity
# - cross_entity
# - report

# 9. evidence
# An array of short evidence bullets sorted from biggest impact to lowest impact.
# Each evidence item must have:
# - rank: integer starting at 1
# - evidence_label: short free-text label inferred from the source, such as "Utilization Evidence", "Review Evidence", "Status Evidence", "General Evidence"
# - bullet: short factual bullet
# - quoted_numbers: array of exact number strings quoted from the source when available

# Evidence rules:
# - Keep bullets short.
# - Rank highest-impact evidence first.
# - Prefer bullets with the largest or most decision-relevant numbers first.
# - Quote numbers exactly as they appear when possible.
# - If there is only one evidence point, return a one-item array.
# - Merge similar evidence from duplicated candidates into the same row.
# - Do not fabricate evidence categories; use "General Evidence" when needed.

# 10. attributes_json
# A JSON object for extra structured details not covered above.
# This can include, when supported:
# - covered_entity_types
# - covered_entities
# - support_count
# - metric_name
# - metric_value
# - metric_unit
# - numerator
# - denominator
# - percentage
# - top_categories
# - status_mix
# - source_paths
# - comparison_basis
# - residual_value
# - missing_fields
# - related_entities
# - section_name
# - raw_snippets
# Use an empty object if nothing else is needed.

# SCHEMA SUMMARY
# Return a compact schema summary with:
# - detected_entity_types: array
# - common_keys_detected: array
# - repeated_shapes: array
# - notes: array

# PATTERN DETECTION RULES
# - Detect patterns from repeated structures, distributions, rankings, dominant categories, concentrations, counts, percentages, zero values, missing values, and cross-entity repetition.
# - Emit cross-entity rows for repeated findings that occur across multiple entities.
# - Emit entity-specific rows only for true outliers, exceptions, or uniquely important single-entity facts.
# - When a distribution has a clearly dominant category, emit a pattern only if it adds distinct information not already covered by another broader pattern.
# - When values are zero or missing, emit a row only if they are unique, material, or clearly notable.
# - Use attributes_json for extra detail rather than adding more top-level columns.

# RETURN FORMAT
# {
#   "schema_summary": {
#     "detected_entity_types": [],
#     "common_keys_detected": [],
#     "repeated_shapes": [],
#     "notes": []
#   },
#   "pattern_table": [
#     {
#       "pattern_id": "",
#       "pattern_title": "",
#       "leadership_summary": "",
#       "description": "",
#       "pattern_type": "",
#       "entity_type": "",
#       "entity_name": null,
#       "scope": "",
#       "evidence": [
#         {
#           "rank": 1,
#           "evidence_label": "General Evidence",
#           "bullet": "",
#           "quoted_numbers": []
#         }
#       ],
#       "attributes_json": {}
#     }
#   ]
# }
# """

In [ ]:
# PATTERN_USER_PROMPT_TEMPLATE = """Analyze the INPUT_JSON dynamically and return a tight generic pattern table.

# Requirements:
# - Do not rely on hardcoded field names, section names, or report templates.
# - Infer repeated entity structures and common patterns directly from the JSON.
# - Return the smallest set of distinct, defensible patterns needed to summarize the input.
# - Do not repeat the same pattern separately for each driver group or section.
# - Merge semantically similar findings into one broader row when possible.
# - Prefer cross-entity patterns over repeated section-level patterns.
# - Only emit entity-specific rows for real outliers, exceptions, or uniquely important facts.
# - Suppress low-signal or obvious universal patterns unless they add meaningful contrast.
# - Keep total rows low; do not let row count scale with the number of drivers.
# - For each pattern, include:
#   - a short business-friendly title
#   - a concise leadership-friendly summary
#   - a factual description
#   - a ranked evidence list from biggest impact to lowest impact
# - In the evidence list:
#   - use a short inferred evidence label
#   - keep bullets short
#   - quote numbers exactly where possible
#   - use "General Evidence" if no specific label is clearly supported
# - Put all extra details into attributes_json.
# - Do not hallucinate.
# - Do not speculate.
# - Do not invent evidence categories, causes, or recommendations.
# - Return only valid JSON.

# INPUT_JSON:
# {INPUT_JSON}
# """

In [17]:
# messages = [
#     {"role": "system", "content": PATTERN_SYSTEM_PROMPT},
#     {"role": "user", "content": PATTERN_USER_PROMPT_TEMPLATE.format(INPUT_JSON=deep_dive)},
# ]

# response = llm.invoke(messages)
# content = str(getattr(response, "content", response)).strip()

In [18]:
# # A deterministic post-filter after the LLM step would make this even safer: dedupe on a normalized key like (pattern_type, core_claim, dominant_dimension).
# df_patterns = pd.DataFrame(json.loads(content)["pattern_table"])
# print(df_patterns.shape)
# df_patterns.head(1)

In [ ]:
RISK_PATTERNS_SYSTEM_PROMPT = """You are a conservative healthcare risk-pattern extraction engine.

Your task is to analyze any INPUT_JSON dynamically and return a flat pattern table.
Do NOT hardcode report sections, field names, or business-specific labels.
Infer repeated structures, entities, metrics, and patterns directly from the input.

PRIMARY OBJECTIVE
Return the smallest set of distinct, high-signal, non-overlapping patterns that are plausibly relevant to payer risk.

This extractor is part of a healthcare risk detection pipeline.
Its purpose is NOT to summarize all patterns.
Its purpose is to surface only patterns that are plausibly relevant to:
- claims leakage
- rising medical cost
- utilization growth
- reimbursement risk
- provider contract risk
- benefit coverage risk
- state mandate / regulatory risk
- review-process risk
- denial / appeal exposure
- unexplained shifts that could materially affect insurer spend or liability

A good pattern:
- captures a meaningful repeated structure,
- summarizes multiple facts into one insight,
- identifies a true outlier / exception,
- and is plausibly relevant to payer cost, leakage, or exposure.

A bad pattern:
- repeats the same idea for each driver type,
- restates an obvious fact already covered by another row,
- creates one row just because a section exists,
- calls out low-signal zeros or descriptive facts with little payer-risk value.

OUTPUT RULES
- Return ONLY valid JSON.
- Do not return markdown.
- The output must be a single JSON object with:
  - "schema_summary"
  - "pattern_table"
- Each row in "pattern_table" must use the exact same keys.
- If a field does not apply, use null.
- If no defensible risk-relevant patterns exist, return an empty pattern_table.
- Preserve exact evidence text where possible.

STRICT NON-HALLUCINATION RULES
- Do not invent facts, numbers, entities, categories, dimensions, causes, recommendations, or evidence labels.
- Do not assume missing fields exist.
- Do not create a pattern unless it is explicitly supported by the input.
- Do not create “Policy Evidence”, “Claims Evidence”, or any other evidence category unless the source supports that framing.
- When unsure about evidence category, use "General Evidence".
- Do not convert weak hints into strong conclusions.
- Do not add interpretations about why the pattern happened.
- Do not add actions, recommendations, or root causes.
- Do not infer financial risk from a pattern unless the structure plausibly supports payer exposure.
- Do not assume a policy change, mandate change, provider contract issue, or benefit design issue occurred.

IMPORTANT TREND RULE
Do NOT claim a metric is "rising", "increasing", "growing", "worsening", or "declining" unless the input explicitly contains time-based evidence or a comparison period that supports that statement.

If the input does NOT contain time-series or benchmark comparison data:
- do NOT emit trend language
- instead use terms like:
  - elevated
  - concentrated
  - skewed
  - outlier
  - unusually high
  - heavily weighted
  - materially varied
  - potential risk signal

ANTI-REPETITION / DEDUPLICATION RULES
- Internally generate candidate patterns first, then deduplicate before producing final output.
- Normalize each candidate into:
  - dimension
  - finding
  - population covered
  - risk relevance
- If two candidates express the same finding on the same dimension with only different supporting examples, merge them into one broader row.
- Do NOT emit one row per driver family for the same normalized finding.
- Prefer one cross-entity row over several near-duplicate rows.
- If the same pattern appears across multiple entity types, merge it into one row with:
  - entity_type = "mixed"
  - scope = "cross_entity"
  - covered entity types stored in attributes_json
- Before emitting any row, test:
  - "Does this row add materially new information not already captured by an existing row?"
  - If NO, do not emit it.
- If two rows would have very similar pattern_title, leadership_summary, description, and risk_relevance, keep only the stronger one.
- Do not let the number of rows track the number of entities, sections, or driver groups.

RISK FILTERING RULES
Only emit a row if at least one of these is supported:
- unusually high or concentrated volume
- unusually high or concentrated share in a potentially cost-sensitive category
- high approval exposure in a sensitive service, provider, geography, or entity
- meaningful variation that could plausibly reflect reimbursement, policy, mandate, contract, or coverage differences
- denial, appeal, or overturn behavior that could affect spend or leakage
- high residual / missing / unclassified component that could hide exposure
- true outlier or exception with plausible payer risk relevance

Suppress patterns that are merely descriptive and do not clearly indicate risk relevance.

# RISK SIGNAL TYPES
# Use one of:
# - volume_increase
# - utilization_shift
# - unit_cost_increase
# - approval_exposure
# - service_mix_shift
# - high_cost_concentration
# - denial_overturn_exposure
# - appeal_exposure
# - provider_concentration_risk
# - geographic_concentration_risk
# - unexplained_outlier
# - missing_or_unclassified_risk
# - reimbursement_rule_sensitivity
# - policy_sensitive_pattern
# - contract_sensitive_pattern
# - mandate_sensitive_pattern
# - benefit_sensitive_pattern
# - other_risk_signal

PATTERN BUDGET
- Target 3 to 7 rows total.
- Only exceed 7 rows when the input clearly contains more than 7 distinct, material, non-overlapping risk patterns.
- Fewer rows is better than repetitive rows.

ROW SCHEMA
Each pattern row must have exactly these keys:

1. pattern_rank
A unique integer for each pattern, starting from 1. Ordered in most impactful pattern to be rank 1. Most impactful is where you would see large volume or variance in metrics.


2. pattern_title
Short title, noun-phrase style, suitable for business readers. Avoid vague term as listed values, use phrases such as "high cost concentration", "large <metric> variance", "large volume variance for <entity>".

3. leadership_summary
One concise leadership-friendly sentence.
Requirements:
- 12 to 30 words
- direct and factual
- include the most important quantified takeaway when possible

4. pattern_type
A generic label such as:
- volume_pattern
- share_pattern
- dominant_category
- concentration
- status_pattern
- review_pattern
- approval_pattern
- denial_pattern
- appeal_pattern
- residual_pattern
- missing_data_pattern
- zero_value_pattern
- cross_entity_pattern
- outlier_pattern
- other_pattern

4. risk_relevance
One concise sentence explaining why the pattern is worth downstream root-cause analysis, without guessing the cause.

8. entity_type
Best inferred entity type from the source.
Entity type is one of the following:
- SRVCAREA_ST_SHRT_DESC: SERVICE AREA STATE SHORT DESCRIPTION is the description of the State Code in the format of 2 character state abbreviation. eg: CA, VA, GA.
- FNL_DRG_NM: FINAL DRG NAME is the name for DIAGNOSIS RELATED GROUP (DRG) CODE. A DRG is a national coding scheme which classifies an inpatient stay based on diagnosis, procedure, discharge status, age and sex.
- 
It is a key value pair where key is "entity_type" and value is the entity type.
eg: {"state": ["CA", "VA"]}

9. entity_name
The entity name if tied to one entity.
If the pattern is cross-entity or report-level, use null.

10. scope
One of:
- entity
- cross_entity
- report

11. evidence
An array of short evidence bullets sorted from biggest impact to lowest impact.
Each evidence item must have:
- rank: integer starting at 1
- evidence_label: short free-text label inferred from the source, such as "Utilization Evidence", "Review Evidence", "Status Evidence", "General Evidence"
- bullet: short factual bullet
- quoted_numbers: array of exact number strings quoted from the source when available

Evidence rules:
- Keep bullets short.
- Rank highest-impact evidence first.
- Prefer bullets with the largest or most decision-relevant numbers first.
- Quote numbers exactly as they appear when possible.
- If there is only one evidence point, return a one-item array.
- Merge similar evidence from duplicated candidates into the same row.
- Do not fabricate evidence categories; use "General Evidence" when needed.

12. attributes_json
A JSON object for extra structured details not covered above.
This can include:
- covered_entity_types
- covered_entities
- support_count
- metric_name
- metric_value
- metric_unit
- numerator
- denominator
- percentage
- top_categories
- status_mix
- source_paths
- comparison_basis
- residual_value
- missing_fields
- related_entities
- section_name
- raw_snippets
Use an empty object if nothing else is needed.

SCHEMA SUMMARY
Return a compact schema summary with:
- detected_entity_types: array
- common_keys_detected: array
- repeated_shapes: array
- notes: array

RETURN FORMAT
{
  "schema_summary": {
    "detected_entity_types": [],
    "common_keys_detected": [],
    "repeated_shapes": [],
    "notes": []
  },
  "pattern_table": [
    {
      "pattern_id": "",
      "pattern_title": "",
      "leadership_summary": "",
      "description": "",
      "pattern_type": "",
      "risk_signal_type": "",
      "risk_relevance": "",
      "entity_type": "",
      "entity_name": null,
      "scope": "",
      "evidence": [
        {
          "rank": 1,
          "evidence_label": "General Evidence",
          "bullet": "",
          "quoted_numbers": []
        }
      ],
      "attributes_json": {}
    }
  ]
}
"""

In [20]:
RISK_PATTERNS_USER_PROMPT_TEMPLATE = """Analyze the INPUT_JSON dynamically and return a tight generic pattern table for healthcare payer risk detection.

Requirements:
- Do not rely on hardcoded field names, section names, or report templates.
- Infer repeated entity structures and common patterns directly from the JSON.
- Return the smallest set of distinct, defensible, risk-relevant patterns needed to summarize the input.
- Only include patterns that could plausibly matter for claims leakage, rising cost, utilization growth, reimbursement exposure, provider contract exposure, benefit coverage exposure, mandate/regulatory exposure, or review-process risk.
- Do not repeat the same pattern separately for each driver group or section.
- Merge semantically similar findings into one broader row when possible.
- Prefer cross-entity patterns over repeated section-level patterns.
- Only emit entity-specific rows for real outliers, exceptions, or uniquely important facts.
- Suppress low-signal or obvious universal patterns unless they add meaningful payer-risk relevance.
- Keep total rows low; do not let row count scale with the number of drivers.
- For each pattern, include:
  - a short business-friendly title
  - a concise leadership-friendly summary
  - a factual description
  - a risk_signal_type
  - a concise risk_relevance sentence
  - a ranked evidence list from biggest impact to lowest impact
- In the evidence list:
  - use a short inferred evidence label
  - keep bullets short
  - quote numbers exactly where possible
  - use "General Evidence" if no specific label is clearly supported
- Put all extra details into attributes_json.
- Do not hallucinate.
- Do not speculate.
- Do not invent causes, trends, evidence categories, or recommendations.
- Do not say a metric is rising or increasing unless the input explicitly contains time-based evidence.
- Return only valid JSON.

INPUT_JSON:
{INPUT_JSON}
"""

In [21]:
messages = [
    {"role": "system", "content": RISK_PATTERNS_SYSTEM_PROMPT},
    {"role": "user", "content": RISK_PATTERNS_USER_PROMPT_TEMPLATE.format(INPUT_JSON=deep_dive)},
]

response = llm.invoke(messages)
content = str(getattr(response, "content", response)).strip()

In [22]:
# A deterministic post-filter after the LLM step would make this even safer: dedupe on a normalized key like (pattern_type, core_claim, dominant_dimension).
df_risk_patterns = pd.DataFrame(json.loads(content)["pattern_table"])
print(df_risk_patterns.shape)
df_risk_patterns.head(1)

(4, 12)

,pattern_id,pattern_title,leadership_summary,description,pattern_type,risk_signal_type,risk_relevance,entity_type,entity_name,scope,evidence,attributes_json
0,pat_drg_ob_delivery_approval_concentration,OB delivery DRG approval concentration,"Three obstetric DRGs account for 7,068 listed authorizations, all 100.00% IP OB Dlvry NB, with 62.99%–68.34% not requiring Medical Necessity review.","The listed obstetric DRGs are entirely concentrated in IP OB Dlvry NB and show approved shares of 79.79%–87.96%, No Decision shares of 4.52%–7.47%, and Partial shares of 5.35%–10.11%.",concentration,approval_exposure,A large block of authorization volume is concentrated in one service family with substantial approval exposure and limited medical-necessity gating.,drg,NaN,cross_entity,"[{'rank': 1, 'evidence_label': 'General Evidence', 'bullet': 'Vaginal Delivery without Sterilization or D&C without CC/MCC has 4,093 auths, is 100.00% IP OB Dlvry NB, and reports 68.34% not requiring Medical Necessity review.', 'quoted_numbers': ['4,093', '100.00%', '68.34%']}, {'rank': 2, 'evidence_label': 'General Evidence', 'bullet': 'Cesarean Section without Sterilization without CC/MCC has 1,570 auths, is 100.00% IP OB Dlvry NB, and reports 67.26% not requiring Medical Necessity review with 87.96% Approved.', 'quoted_numbers': ['1,570', '100.00%', '67.26%', '87.96%']}, {'rank': 3, 'evidence_label': 'General Evidence', 'bullet': 'Vaginal Delivery without Sterilization or D&C with CC has 1,405 auths, is 100.00% IP OB Dlvry NB, with 79.79% Approved, 10.11% Partial, and 7.47% No Decision.', 'quoted_numbers': ['1,405', '100.00%', '79.79%', '10.11%', '7.47%']}]","{'covered_entity_types': ['drg'], 'covered_entities': ['Vaginal Delivery without Sterilization or D&C without CC/MCC', 'Cesarean Section without Sterilization without CC/MCC', 'Vaginal Delivery without Sterilization or D&C with CC'], 'support_count': 3, 'metric_name': 'listed_authorizations', 'metric_value': 7068, 'metric_unit': 'authorizations', 'top_categories': ['IP OB Dlvry NB'], 'source_paths': ['top_drg_drivers.drgs']}"

In [23]:
df_risk_patterns.leadership_summary

0                    Three obstetric DRGs account for 7,068 listed authorizations, all 100.00% IP OB Dlvry NB, with 62.99%–68.34% not requiring Medical Necessity review.
1    Listed providers range from 17.64% to 82.89% requiring Medical Necessity review, and some have only 34.79%–38.96% classified across the two reported review buckets.
2                                GRADY MEMORIAL HOSPITAL shows 18.41% Partial status on 516 authorizations, roughly double the other listed providers’ 4.93%–9.43% range.
3                                                 CO has 24 appeals from 138 denials (17.39%) and 3 overturns, the largest denial-related volume among the listed states.
Name: leadership_summary, dtype: str

In [24]:
s = ""
for _, row in df_risk_patterns.iterrows():
    s += f"{row.leadership_summary}\n"
    for e in row.evidence:
        s += f"- {e['bullet']}\n"
    s += "-" * 80 + "\n"
print(s)

Three obstetric DRGs account for 7,068 listed authorizations, all 100.00% IP OB Dlvry NB, with 62.99%–68.34% not requiring Medical Necessity review.
- Vaginal Delivery without Sterilization or D&C without CC/MCC has 4,093 auths, is 100.00% IP OB Dlvry NB, and reports 68.34% not requiring Medical Necessity review.
- Cesarean Section without Sterilization without CC/MCC has 1,570 auths, is 100.00% IP OB Dlvry NB, and reports 67.26% not requiring Medical Necessity review with 87.96% Approved.
- Vaginal Delivery without Sterilization or D&C with CC has 1,405 auths, is 100.00% IP OB Dlvry NB, with 79.79% Approved, 10.11% Partial, and 7.47% No Decision.
--------------------------------------------------------------------------------
Listed providers range from 17.64% to 82.89% requiring Medical Necessity review, and some have only 34.79%–38.96% classified across the two reported review buckets.
- GRADY MEMORIAL HOSPITAL reports 17.64% requiring Medical Necessity review and 21.32% not requiring it, leaving most authorizations outside the two reported buckets.
- EMORY DECATUR HOSPITAL reports 20.27% requiring Medical Necessity review and 14.52% not requiring it, again leaving most authorizations outside the two reported buckets.
- CEDARS-SINAI MEDICAL CENTER reports 82.89% requiring Medical Necessity review and 15.68% not requiring it.
- JOHN PETER SMITH HOSPITAL reports 80.15% requiring Medical Necessity review and 19.85% not requiring it.
--------------------------------------------------------------------------------
GRADY MEMORIAL HOSPITAL shows 18.41% Partial status on 516 authorizations, roughly double the other listed providers’ 4.93%–9.43% range.
- GRADY MEMORIAL HOSPITAL has 95 Partial authorizations out of 516, accounting for 18.41%.
- Other listed providers report Partial shares of 9.43% at CEDARS-SINAI MEDICAL CENTER, 4.93% at EMORY DECATUR HOSPITAL, and 8.46% at JOHN PETER SMITH HOSPITAL.
- Its service mix is heavily concentrated in IP Med/Surg with 479 authorizations, accounting for 92.83%.
--------------------------------------------------------------------------------
CO has 24 appeals from 138 denials (17.39%) and 3 overturns, the largest denial-related volume among the listed states.
- Of 138 denied authorizations in CO, Appealed authorizations are 24, accounting for 17.39%.
- CO also reports 3 overturned cases, accounting for 2.17% of total denials, and 15 upheld cases, accounting for 10.87%.
- ME reports 24 denied authorizations with 3 appeals, accounting for 12.50%, and 0 overturned cases.
--------------------------------------------------------------------------------

In [25]:
df_insights.INSIGHTS_TYPE.value_counts()

INSIGHTS_TYPE
KEY_INSIGHT    12
DEEP_DIVE      12
Name: count, dtype: int64

In [26]:
import traceback

In [27]:
op = []
for idx, insight in df_insights[df_insights.INSIGHTS_TYPE == 'DEEP_DIVE'].copy()[0:2].iterrows():
    deep_dive = insight.JSON_TXT
    try:
        messages = [
            {"role": "system", "content": RISK_PATTERNS_SYSTEM_PROMPT},
            {"role": "user", "content": RISK_PATTERNS_USER_PROMPT_TEMPLATE.format(INPUT_JSON=deep_dive)},
        ]
        response = llm.invoke(messages)
        content = str(getattr(response, "content", response)).strip()
        df_risk_patterns = pd.DataFrame(json.loads(content)["pattern_table"])
        s = ""
        for _, row in df_risk_patterns.iterrows():
            s += f"{row.leadership_summary}\n"
            for e in row.evidence:
                s += f"- {e['bullet']}\n"
            s += "-" * 80 + "\n"
        insight['PATTERN'] = s
    except:
        print(f"Error processing insight row: {idx}")
        print(traceback.format_exc())
        insight['PATTERN'] = ""
    op.append(insight)
    
df_output = pd.DataFrame(op)
df_output.shape

(2, 9)

In [29]:
df_output.to_excel("2026-06-23_patterns_output.xlsx", index=False)

In [32]:
df_risk_patterns[["leadership_summary", "evidence"]]

,leadership_summary,evidence
0,"GRADY lists only '91' require and '110' do not require review out of '516', and a top DRG classifies only '1,759' plus '323' of '3,397' approvals.","[{'rank': 1, 'evidence_label': 'Review Evidence', 'bullet': 'CO lists '2,470' requiring review and '884' not requiring review out of '5,898' total authorizations.', 'quoted_numbers': ['2,470', '884', '5,898', '41.88%', '14.99%']}, {'rank': 2, 'evidence_label': 'Approval Evidence', 'bullet': 'Vaginal Delivery without Sterilization or D&C without CC/MCC lists '1,759' medical-necessity approvals and '323' administrative approvals out of '3,397' approved authorizations.', 'quoted_numbers': ['1,759', '323', '3,397', '51.78%', '9.51%']}, {'rank': 3, 'evidence_label': 'Review Evidence', 'bullet': 'GRADY MEMORIAL HOSPITAL lists '91' requiring review and '110' not requiring review out of '516' total authorizations.', 'quoted_numbers': ['91', '110', '516', '17.64%', '21.32%']}, {'rank': 4, 'evidence_label': 'Review Evidence', 'bullet': 'EMORY DECATUR HOSPITAL lists '74' requiring review and '53' not requiring review out of '365' total authorizations.', 'quoted_numbers': ['74', '53', '365', '20.27%', '14.52%']}]"
1,"All three listed DRGs are '100.00%' IP OB Dlvry NB, with '79.79%' to '87.96%' approved and '62.99%' to '68.34%' not requiring review.","[{'rank': 1, 'evidence_label': 'Service Evidence', 'bullet': 'Vaginal Delivery without Sterilization or D&C without CC/MCC: '4,093' auths, '100.00%' IP OB Dlvry NB, '68.34%' do not require review, '83.00%' approved.', 'quoted_numbers': ['4,093', '100.00%', '68.34%', '83.00%']}, {'rank': 2, 'evidence_label': 'Service Evidence', 'bullet': 'Cesarean Section without Sterilization without CC/MCC: '1,570' auths, '100.00%' IP OB Dlvry NB, '67.26%' do not require review, '87.96%' approved.', 'quoted_numbers': ['1,570', '100.00%', '67.26%', '87.96%']}, {'rank': 3, 'evidence_label': 'Service Evidence', 'bullet': 'Vaginal Delivery without Sterilization or D&C with CC: '1,405' auths, '100.00%' IP OB Dlvry NB, '62.99%' do not require review, '79.79%' approved.', 'quoted_numbers': ['1,405', '100.00%', '62.99%', '79.79%']}, {'rank': 4, 'evidence_label': 'Status Evidence', 'bullet': 'The same DRGs also show decision friction, including '7.26%' No Decision and '7.16%' Partial, '4.52%' No Decision and '5.35%' Partial, and '7.47%' No Decision and '10.11%' Partial.', 'quoted_numbers': ['7.26%', '7.16%', '4.52%', '5.35%', '7.47%', '10.11%']}]"
2,"GRADY MEMORIAL HOSPITAL has '95' partial authorizations, or '18.41%' of '516', the highest partial share among listed providers.","[{'rank': 1, 'evidence_label': 'Status Evidence', 'bullet': 'GRADY MEMORIAL HOSPITAL has '95' Partial authorizations, '18.41%' of '516' total.', 'quoted_numbers': ['95', '18.41%', '516']}, {'rank': 2, 'evidence_label': 'Approval Evidence', 'bullet': 'GRADY MEMORIAL HOSPITAL has '411' Approved authorizations, '79.65%' of total.', 'quoted_numbers': ['411', '79.65%']}, {'rank': 3, 'evidence_label': 'General Evidence', 'bullet': 'Other listed provider partial shares are '9.43%' at CEDARS-SINAI MEDICAL CENTER, '8.46%' at JOHN PETER SMITH HOSPITAL, and '4.93%' at EMORY DECATUR HOSPITAL.', 'quoted_numbers': ['9.43%', '8.46%', '4.93%']}]"
3,"CO has the largest denial and appeal volume in the report: '138' not approved, '24' appealed, and '3' overturned out of '5,898' auths.","[{'rank': 1, 'evidence_label': 'Denial Evidence', 'bullet': 'CO has '138' denied authorizations; '24' were appealed, '3' overturned, and '15' upheld.', 'quoted_numbers': ['138', '24', '3', '15', '17.39%', '2.17%', '10.87%']}, {'rank': 2, 'evidence_label': 'Status Evidence', 'bullet': 'CO has '5,221' Approved authorizations ('88.52%') and '485' Partial authorizations ('8.22%') out of '5,898' total.', 'quoted_numbers': ['5,221', '88.52%', '485', '8.22%', '5,898']}, {'rank': 3, 'evidence_label': 'Denial Evidence', 'bullet': 'ME shows smaller state denial activity with '24' denied, '3' appealed, and '0.00%' overturned.', 'quoted_numbers': ['24', '3', '0.00%', '12.50%']}]"